import {StyleSheet} from 'react-native';
import VehoColors from './../../VehoColors';

export default StyleSheet.create({
  containerAvoid: {
    flexGrow: 1,
    width: '100%',
    flexDirection: 'column',
    alignSelf: 'stretch',
    alignItems: 'center',
    justifyContent: 'flex-start',
    backgroundColor: VehoColors.background,
  },
  container: {
    flex: 4,
    alignSelf: 'stretch',
    flexDirection: 'column',
    alignItems: 'center',
  },
  containerScroll: {
    flexGrow: 1,
    alignSelf: 'stretch',
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
  },
  profilePicContainer:{
    flex: 0,
    padding: 10,
    alignSelf: 'stretch',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  inputContainer: {
    flex: 0,
    alignSelf: 'stretch',
    marginVertical: 10,
  },
  carouselSelectionContainer:{
    flex: 0,
    width: '100%',
    paddingLeft: 20,
    flexDirection: 'row',
    alignItems: 'center',
  },
  carouselSelectionContainercon:{
    width: '100%',
    marginVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',

  },
  buttonContainer: {
    alignSelf: 'stretch',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: 10,
    paddingBottom: 10,
  },
  title: {
    width: '100%',
    color: VehoColors.white,
    textAlign: 'center',
    fontSize: 26,
    fontWeight: 'bold',
    marginTop: 24,
  },
  profilePic: {
    backgroundColor: VehoColors.input,
    width: 130,
    height: 130,
    borderRadius: 360,
    elevation: 3,
  },
  subtitle: {
    width: '80%',
    color: VehoColors.white,
    textAlign: 'left',
    fontSize: 20,
    fontWeight: 'bold',
  },
  button: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#13265f',
    width: '100%',
    borderRadius: 10,
    marginBottom: 10,
    elevation: 3,
  },
  logOutButton: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#E22583',
    width: '100%',
    borderRadius: 10,
    marginBottom: 10,
    elevation: 3,
  },
});